### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rossimo** [jmhobbs/cultofthepartyparrot.com#17]
What's the license on party parrot? A slack group I'm a part of has grown attached to :partyparrot:, and I'd like to have some merchandise made.

**Comment by jmhobbs** [comment]
Hey @rossimo!

We still don't know the origin of the first gif, so that particular piece is vague.

The [SVG](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/parrot.svg) is [CC-by-SA](https://creativecommons.org/licenses/by-sa/4.0/).  Same with [parrot dad](https://github.com/jmhobbs/cultofthepartyparrot.com/blob/master/parrots/parrotdad.gif).

There is currently a [:parrot: shirt on Cotton Bureau](https://cottonbureau.com/products/parrot), in case that interests you.

I'll add a LICENSE file to the repo, thanks for bringing this up.

Have a great day!

**Comment by rossimo** [comment]
Thanks! http://rpg-talk.com/
